parameters:
  UserId:
    name: id
    in: path
    description: User id
    required: true
    type: string
  CreteProducts:
    name: CreateProduct
    in: body
    description: Product data
    required: true
    schema:
      $ref: '#/definitions/CreateSingleProduct'
  ProductId:
    name: id
    in: path
    description: Product id
    required: true
    type: string
  CityId:
    name: id
    in: path
    description: City id
    required: false
    type: string
  UpdatedOrNewCity:
    in: body
    name: body
    description: Login user data
    required: true
    schema:
      $ref: '#/definitions/Cities'
